sudo: required

services:
  - docker
  
branches:
  only: 
    - master
    - staging-ci

install:
  - git clone https://github.com/radioberry/docker-aipo.git

before_script:
#  - docker build -t docker-aipo .
  - docker ps
  
script:
  - docker ps
  - docker-compose up -d
  
after_script:
  - docker images
  - docker ps
  - docker volume ls
  
notifications:
slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
