sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging-ci

install:
  - git clone https://github.com/radioberry/docker-aipo.git

before_script:
  - docker-compose build .

script:

  - docker-compose up -d

after_script:
  - docker-compose ps
  - docker volume ls
  - ls /srv/aipo/
notifications:
slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
