sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging-ci

install:

before_script:
  - docker-compose -f docker-compose-ci.yml build .

script:
  - docker-compose -f docker-compose-ci.yml up -d

after_script:
  - docker-compose ps
  - docker-compose logs aipo
notifications:
slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
