sudo: required

services:
  - docker
  
branches:
  only: 
    - master
    - staging-ci

install:
  - git clone https://github.com/radioberry/docker-aipo.git

before_script:
  - docker build -t docker-aipo .
#  - docker ps
#  - ls
#  - cd docker-aipo
#  - ls

  
script:
  - docker ps
#  - docker-compose up -d
#  docker run --detach --publish 8080:80 --name aipo --restart=always --volume /srv/aipo/data:/srv/aipo/postgres/data docker-aipo:latest
  
after_script:
  - docker images
  - docker ps
  - docker volume ls
  - ls /srv/aipo/  
notifications:
slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
