sudo: required

services:
  - docker
  
branches:
  only: 
    - master
    - staging-ci

install:
  - git clone https://github.com/radioberry/docker-aipo.git

before_script:
  - docker ps

  
script:
  - docker-compose up -d
  
after_script:
  - docker images
  - docker ps
  - docker volume ls
  - ls /srv/aipo/
  - curl aipo
  - curl localhost:8080
notifications:
slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
