version: '2'
services:
#  https-portal:
#    image: steveltn/https-portal:1
#    ports:
#      - '80:80'
#      - '443:443'
#    links:
#      - aipo
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
    # Any domain aipo.example.com
#      DOMAINS: 'aipo.example.com -> http://aipofront'
  aipo:
    image: diorama/aipo:latest
    ports:
      - "8080:80"
    restart: always
    volumes:
      - postgresdata:/srv/aipo/postgres/data
volumes:
  postgresdata:
    driver: local
